// Proyectos
export const FORMULARIO_PROYECTO = "FORMULARIO_PROYECTO";
export const OBTENER_PROYECTO = "OBTENER_PROYECTO";
export const CREAR_PROYECTO = "CREAR_PROYECTO";
export const PROYECTO_ACTUAL = "PROYECTO_ACTUAL";
export const ELIMINAR_PROYECTO = "ELIMINAR_PROYECTO";

//tareas
export const OBTENER_TAREA = "OBTENER_TAREA";
export const CREAR_TAREA = "CREAR_TAREA";
export const ELIMINAR_TAREA = "ELIMINAR_TAREA";
export const ESTADO_TAREA = "ESTADO_TAREA";
export const TAREA_ACTUAL = "TAREA_ACTUAL";
export const EDITAR_TAREA = "EDITAR_TAREA";
